vim.o.clipboard = "unnamedplus"
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.softtabstop = 4
vim.o.wrap = false
vim.o.signcolumn = "yes"
vim.o.number = true
vim.o.relativenumber = true
vim.opt.viewoptions = { "folds", "cursor", "curdir", "slash", "unix" }
